# Generated by Django 6.0.7 on 2026-07-28 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MessManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('breakfast', models.IntegerField(default=0)),
                ('lunch', models.IntegerField(default=0)),
                ('dinner', models.IntegerField(default=0)),
                ('total_meals', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mess_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MessManagement.messmembership')),
                ('mess_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MessManagement.messseason')),
            ],
        ),
    ]
