# Generated by Django 6.0.7 on 2026-08-13 20:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManagement', '0001_initial'),
        ('MessManagement', '0013_notices_is_pinned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meals',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterField(
            model_name='meals',
            name='breakfast',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='meals',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meals',
            name='dinner',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='meals',
            name='lunch',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='meals',
            name='mess_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='MessManagement.messmembership'),
        ),
        migrations.AlterField(
            model_name='meals',
            name='mess_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='MessManagement.messseason'),
        ),
        migrations.AlterUniqueTogether(
            name='meals',
            unique_together={('mess_season', 'mess_member', 'date')},
        ),
    ]
