# Generated by Django 6.0.7 on 2026-10-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealManagement', '0002_alter_meals_options_alter_meals_breakfast_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='meals',
            table='meals',
        ),
    ]
