# Generated by Django 6.0.7 on 2026-10-03 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MealManagement', '0003_alter_meals_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='breakfast',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='meals',
            name='dinner',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='meals',
            name='lunch',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='meals',
            name='total_meals',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
