# Generated by Django 6.0.7 on 2026-10-03 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthManagement', '0002_alter_passwordresetotp_table_alter_user_table'),
        ('MessManagement', '0017_notices_belong_to_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='MessManagement.messmembership'),
        ),
    ]
