# Generated by Django 6.0.7 on 2026-10-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthManagement', '0003_user_current_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
