# Generated by Django 6.0.7 on 2026-10-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DepositManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deposit',
            table='deposits',
        ),
    ]
