# Generated by Django 6.0.7 on 2026-10-02 17:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepositManagement', '0002_alter_deposit_table'),
        ('MessManagement', '0015_alter_mess_table_alter_messmembership_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddField(
            model_name='deposit',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='deposit',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits_recorded', to='MessManagement.messmembership'),
        ),
    ]
