# Generated by Django 6.0.7 on 2026-10-04 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_version', models.CharField(default='1.0.0', help_text='Newest app version. Older apps are offered an optional update.', max_length=20, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+){0,2}$', 'Use a version like 1.4.2.')])),
                ('minimum_version', models.CharField(default='1.0.0', help_text='Apps older than this must update before they can be used.', max_length=20, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+){0,2}$', 'Use a version like 1.4.2.')])),
                ('update_message', models.TextField(blank=True, help_text="Shown with the update prompt. Leave empty for the app's default text.")),
                ('android_store_url', models.URLField(blank=True)),
                ('ios_store_url', models.URLField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='While on, the app shows the maintenance screen and the API answers 503.')),
                ('maintenance_message', models.TextField(blank=True, default="We're improving the app. Please check back soon.")),
                ('maintenance_until', models.DateTimeField(blank=True, help_text='Expected end, shown to users. Optional.', null=True)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App setting',
                'verbose_name_plural': 'App settings',
                'db_table': 'app_settings',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'Bengali'), ('ar', 'Arabic')], default='en', max_length=5)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower comes first.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'faqs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('privacy-policy', 'Privacy policy'), ('terms-and-conditions', 'Terms and conditions')], max_length=40)),
                ('language', models.CharField(choices=[('en', 'English'), ('bn', 'Bengali'), ('ar', 'Arabic')], default='en', max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text="Plain text. Separate paragraphs with a blank line; a line starting with '# ' is a heading and '- ' a bullet.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'content_pages',
                'ordering': ['kind', 'language'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'language'), name='one_page_per_kind_and_language')],
            },
        ),
    ]
