# Generated by Django 6.0.7 on 2026-07-28 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MessManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundsBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='income', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funds_breakdown_mess', to='MessManagement.mess')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds_season', to='MessManagement.messseason')),
            ],
        ),
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funds_mess', to='MessManagement.mess')),
                ('funds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds_breakdown', to='FundManagement.fundsbreakdown')),
            ],
        ),
    ]
