# Generated by Django 6.0.7 on 2026-10-02 18:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundManagement', '0002_alter_funds_table_alter_fundsbreakdown_table'),
        ('MessManagement', '0015_alter_mess_table_alter_messmembership_table_and_more'),
    ]

    operations = [
        # Drop the old (empty, unused) tables first: the new model reuses the `funds` table name.
        migrations.RemoveField(
            model_name='fundsbreakdown',
            name='mess',
        ),
        migrations.RemoveField(
            model_name='fundsbreakdown',
            name='season',
        ),
        migrations.DeleteModel(
            name='Funds',
        ),
        migrations.DeleteModel(
            name='FundsBreakdown',
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds_recorded', to='MessManagement.messmembership')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='MessManagement.messseason')),
            ],
            options={
                'db_table': 'funds',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
