# Generated by Django 6.0.7 on 2026-07-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessManagement', '0002_notices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messmembership',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messseason',
            name='end_date',
            field=models.DateField(default=None),
        ),
    ]
