# Generated by Django 6.0.7 on 2026-07-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessManagement', '0003_alter_messmembership_left_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messmembership',
            name='left_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
