# Generated by Django 6.0.7 on 2026-07-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessManagement', '0004_alter_messmembership_left_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messseason',
            name='end_date',
            field=models.DateField(),
        ),
    ]
