# Generated by Django 6.0.7 on 2026-07-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessManagement', '0005_alter_messseason_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messseason',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
