# Generated by Django 6.0.7 on 2026-07-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessManagement', '0006_alter_messseason_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mess',
            name='act_manager',
        ),
        migrations.RemoveField(
            model_name='mess',
            name='manager',
        ),
    ]
