# Generated by Django 6.0.7 on 2026-07-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessManagement', '0007_remove_mess_act_manager_remove_mess_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='messmembership',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('member', 'Member'), ('acting_manager', 'Acting Manager')], default='member', max_length=20),
        ),
    ]
