# Generated by Django 6.0.7 on 2026-07-30 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessManagement', '0008_messmembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messseason',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
