# Generated by Django 6.0.7 on 2026-08-01 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessManagement', '0010_alter_messmembershiprequest_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='messmembershipinvitation',
            name='mess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_invitations', to='MessManagement.mess'),
        ),
        migrations.AlterField(
            model_name='messmembershipinvitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messmembershiprequest',
            name='mess',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess_requests', to='MessManagement.mess'),
        ),
        migrations.AlterField(
            model_name='messmembershiprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
