# Generated by Django 6.0.7 on 2026-08-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessManagement', '0011_alter_messmembershipinvitation_mess_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messmembershipinvitation',
            unique_together=set(),
        ),
    ]
