# Generated by Django 6.0.7 on 2026-08-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessManagement', '0012_alter_messmembershipinvitation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
