# Generated by Django 6.0.7 on 2026-10-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MessManagement', '0014_mess_leadership_and_invite_code'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mess',
            table='messes',
        ),
        migrations.AlterModelTable(
            name='messmembership',
            table='mess_memberships',
        ),
        migrations.AlterModelTable(
            name='messmembershipinvitation',
            table='mess_membership_invitations',
        ),
        migrations.AlterModelTable(
            name='messmembershiprequest',
            table='mess_membership_requests',
        ),
        migrations.AlterModelTable(
            name='messseason',
            table='mess_seasons',
        ),
        migrations.AlterModelTable(
            name='notices',
            table='notices',
        ),
    ]
