# Generated by Django 6.0.7 on 2026-10-03 16:32

from django.db import migrations, models


def keep_newest_pinned_notice(apps, schema_editor):
    """Before the constraint: unpin all but the newest pinned notice of each mess."""
    Notices = apps.get_model('MessManagement', 'Notices')
    seen_messes = set()
    for notice in Notices.objects.filter(is_pinned=True).order_by('mess_id', '-created_at', '-id'):
        if notice.mess_id in seen_messes:
            Notices.objects.filter(pk=notice.pk).update(is_pinned=False)
        else:
            seen_messes.add(notice.mess_id)


class Migration(migrations.Migration):

    dependencies = [
        ('MessManagement', '0015_alter_mess_table_alter_messmembership_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notices',
            options={'ordering': ['-is_pinned', '-created_at', '-id']},
        ),
        migrations.RunPython(keep_newest_pinned_notice, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='notices',
            constraint=models.UniqueConstraint(condition=models.Q(('is_pinned', True)), fields=('mess',), name='one_pinned_notice_per_mess'),
        ),
    ]
