# Generated by Django 6.0.7 on 2026-10-03 18:43

from django.db import migrations, models


def mark_cancelled_requests(apps, schema_editor):
    """Requests withdrawn before this status existed were stored as rejected with a 'Cancelled…' note."""
    Request = apps.get_model('MessManagement', 'MessMemberShipRequest')
    Request.objects.filter(status='rejected', response_message__startswith='Cancelled').update(status='cancelled')


class Migration(migrations.Migration):

    dependencies = [
        ('MessManagement', '0017_notices_belong_to_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messmembershiprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.RunPython(mark_cancelled_requests, migrations.RunPython.noop),
    ]
