# Generated by Django 6.0.7 on 2026-10-04 14:20

import django.core.validators
from django.db import migrations, models


def end_closed_seasons(apps, schema_editor):
    """Seasons closed by the old one-season flow (is_active=False) become ended."""
    MessSeason = apps.get_model('MessManagement', 'MessSeason')
    for season in MessSeason.objects.filter(is_active=False, end_date__isnull=True):
        season.end_date = season.updated_at.date()
        season.save(update_fields=['end_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('MessManagement', '0018_join_request_cancelled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess',
            name='auto_create_season',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mess',
            name='auto_create_season_day',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(28)]),
        ),
        migrations.AddField(
            model_name='mess',
            name='last_auto_season_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messseason',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(end_closed_seasons, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='messseason',
            name='is_active',
        ),
    ]
