# Generated by Django 6.0.7 on 2026-10-04 14:22

import django.db.models.deletion
from django.db import migrations, models


def target_running_season(apps, schema_editor):
    """Pending invites from before seasons were chosen go to their mess's newest running season."""
    Invitation = apps.get_model('MessManagement', 'MessMemberShipInvitation')
    MessSeason = apps.get_model('MessManagement', 'MessSeason')
    for invite in Invitation.objects.filter(status='pending', season__isnull=True):
        invite.season = (
            MessSeason.objects.filter(mess_id=invite.mess_id, end_date__isnull=True, is_disabled=False)
            .order_by('-start_date', '-id').first()
        )
        invite.save(update_fields=['season'])

class Migration(migrations.Migration):

    dependencies = [
        ('MessManagement', '0019_seasons_run_in_parallel'),
    ]

    operations = [
        migrations.AddField(
            model_name='messmembershipinvitation',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='MessManagement.messseason'),
        ),
        migrations.AddField(
            model_name='messmembershiprequest',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests', to='MessManagement.messseason'),
        ),
        migrations.RunPython(target_running_season, migrations.RunPython.noop),
    ]
